ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/3 - User - Sign Up.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/5 - ACL.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/6 - Installation.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Object Protocols/Protocols/Objectable.swift
Sources/ParseSwift/Parse Types/Internal/BaseParseInstallation.swift
Sources/ParseSwift/Parse Types/Internal/BaseParseUser.swift
Sources/ParseSwift/Parse Types/ParseACL.swift
Tests/ParseSwiftTests/ACLTests.swift
Tests/ParseSwiftTests/ParseEncoderTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectBatchTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParsePointerTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Looks like the compiler can't use the ACL as a type when the property type of an Object is named ACL. So going back to ParseACL to differentiate.

Switch ACL to ParseACL

---

.github/workflows/swift.yml
.spi.yml
ParseSwift.xcodeproj/project.pbxproj
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (tvOS).xcscheme
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/API/URLSession+extensions.swift
TestHostTV/AppDelegate.swift
TestHostTV/Assets.xcassets/AccentColor.colorset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
TestHostTV/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
TestHostTV/Assets.xcassets/Contents.json
TestHostTV/Base.lproj/LaunchScreen.storyboard
TestHostTV/Base.lproj/Main.storyboard
TestHostTV/Info.plist
TestHostTV/ViewController.swift

There's a bug where the specified callback queue was being used in the incorrect place causing crashing in apps.
This most likely fixes the random crash from the tests that was occurring. This PR specifically addresses the following:

Fix callbackqueue bug

---

.codecov.yml
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/API/BatchUtils.swift
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/Object Protocols/ParseUser.swift
Sources/ParseSwift/Parse.swift
Tests/ParseSwiftTests/ACLTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Fix password saving to Keychain after user login

---

.codecov.yml
Sources/ParseSwift/Coding/ParseEncoder.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

Fix encoding object arrays

---

.codecov.yml
.github/workflows/ci.yml
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/3 - User - Sign Up.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/6 - Installation.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Object Protocols/ParseInstallation.swift
Sources/ParseSwift/Object Protocols/ParseObject.swift
Sources/ParseSwift/Object Protocols/ParseUser.swift
Sources/ParseSwift/Object Protocols/Protocols/Deletable.swift
Sources/ParseSwift/Object Protocols/Protocols/Fetchable.swift
Sources/ParseSwift/Object Protocols/Protocols/Queryable.swift
Sources/ParseSwift/Object Protocols/Protocols/Saveable.swift
Sources/ParseSwift/Parse Types/Query.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift
carthage.sh

In order to get this, User and Installation protocols have to implement it's own versions of some of the ParseObject methods. Not necessarily a problem, but adds more code to the `ParseUser` and `ParseInstallation` protocols. Also requires some additional testing outside of the `ParseObject` tests of these methods.

Update keychains of ParseUser and ParseInstallation

---

ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Parse Types/ParseGeoPoint.swift
Sources/ParseSwift/Parse Types/Query.swift
Tests/ParseSwiftTests/ParseGeoPointTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

This makes `ParseGeoPoint` consistent with the rest of the SDK.
`File` will be changed to `ParseFile` in a future PR.

Change GeoPoint to ParseGeoPoint

---

Package.swift
ParseSwift.playground/Pages/10 - Cloud Code.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/9 - Files.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
ParseSwift.podspec
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Types/ParseCloud.swift
Tests/ParseSwiftTests/ParseCloudTests.swift

Switch CloudCode to similar syntax as JS SDK. Update podspec

---

.codecov.yml
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Tests/ParseSwiftTests/ParseObjectBatchTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

Fixes #47. Previous commits didn't enforce `ParseObjects` going through the ParseEncoder. Since they go through now, there was a bug in the encoder when objects were already saved. They were automatically converted to Pointers, even if they were themselves. This caused issues when attempting to saveAll as 1) there were keys the server didn't like 2) No other key/value info wasn't being sent during the update

Bug fix: issue when encoding objects that are already saved

---

Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Bug fix: query constraint ==

---

.codecov.yml
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/API/ParseURLSessionDelegate.swift
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/ParseCloud.swift
Sources/ParseSwift/Types/ParseFile.swift
Sources/ParseSwift/Types/Pointer.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

I'm hoping this fixes the random failure that only occurred in the 100 thread tests that has been hard to find...

Improve threading

---

ParseSwift.playground/Pages/12 - Roles and Relations.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/3 - User - Sign Up.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
ParseSwift.podspec
Scripts/jazzy.sh
Sources/ParseSwift/Internal/BaseParseUser.swift
Sources/ParseSwift/Objects/ParseUser.swift
Tests/ParseSwiftTests/ParseACLTests.swift
Tests/ParseSwiftTests/ParseAnonymousTests.swift
Tests/ParseSwiftTests/ParseAppleTests.swift
Tests/ParseSwiftTests/ParseAuthenticationTests.swift
Tests/ParseSwiftTests/ParseConfigTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift
Tests/ParseSwiftTests/ParseSessionTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Removing extra sessionToken in ParseUser from 1.0.0 so devs don't add it.
Pod will show as 1.0.1.
To put next versions in sync, the next release should be 1.0.1 or 1.1.0.

Minor update

---

.github/workflows/ci.yml
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
Tests/ParseSwiftTests/KeychainStoreTests.swift
Tests/ParseSwiftTests/NetworkMocking/MockURLProtocol.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseOperationTests.swift
Tests/ParseSwiftTests/ParseRelationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift

Builds on Linux!
The testsuite has revealed the following limitations on Linux:
- `ParseFile` currently doesn't work. This is because the SDK is currently setup for iOS, macOS, etc. There's probably a simple way to access the file system on Linux via Swift that can be added at some point.
- `ParseLiveQuery` currently doesn't work in the latest version of Swift (5.3.2). `FoundationNetworking` doesn't have `URLWebSocketSessionTask`. The solution is to wait to for web socket support to be added in a newer version of Swift.
- `Keychain` currently doesn't work in the latest version of Swift (5.3.2). The workaround for this has already been added in the SDK. Devs need to conform to `ParseKeyValueStore` if they want to persist the current user, installation, and config. Otherwise they only exist …

Linux support

---

.swiftlint.yml
CHANGELOG.md
ParseSwift.playground/Pages/12 - Roles and Relations.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/13 - Operations.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/14 - Config.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/9 - Files.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
Sources/ParseSwift/API/API.swift
Tests/ParseSwiftTests/APICommandTests.swift

Add Idempotency

---

.github/workflows/ci.yml
Sources/ParseSwift/Storage/ParseFileManager.swift

On Linux, Bundle.main.bundleIdentifier is nil.
This commit creates a custom bundle identifier instead.
With this change, tests for `ParseFileManager` seem to pass on Linux:
```
$ swift test --enable-test-discovery --filter ParseFileManagerTests
[9/9] Linking ParseSwiftPackageTests.xctest
Test Suite 'Selected tests' started at 2021-01-24 19:01:54.641
Test Suite 'ParseFileManagerTests' started at 2021-01-24 19:01:54.642
Test Case 'ParseFileManagerTests.testCopyItem' started at 2021-01-24 19:01:54.642
Test Case 'ParseFileManagerTests.testCopyItem' passed (0.052 seconds)
Test Case 'ParseFileManagerTests.testMoveContentsOfDirectory' started at 2021-01-24 19:01:54.693
Test Case 'ParseFileManagerTests.testMoveContentsOfDirectory' passed (0.048 seconds)
Test Case …
```

Workaround for empty main bundle identifier on Linux

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/LiveQuery/Subscription.swift
Sources/ParseSwift/LiveQuery/SubscriptionCallback.swift

the new subscription properties won't accessible outside the framework

Expose Subscription properties

---

.github/workflows/ci.yml
.github/workflows/release.yml
Sources/ParseSwift/LiveQuery/Subscription.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

This PR adds the query pull methods such as `find`, `first`, `count`, and `aggregate` to `Subscription` so they can be accessed in a SwiftUI view model next to LiveQuery `subscribe`, `event`, and `unsubscribe`.
The minimizes the need for a developer to have to start from scratch when creating their own view model and gives them the power of LiveQuery alongside traditional Parse queries out-of-the-box.
The PR is non-breaking...

Add pull responses to Subscription for publishable VM

---

ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground

LiveQuery SwiftUI example in playgrounds 

---

.github/workflows/ci.yml
CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Internal/Data+hexString.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift

Support for PushNotifications

---

CHANGELOG.md
Sources/ParseSwift/Types/ParseACL.swift
Tests/ParseSwiftTests/ParseACLTests.swift

Improve acl

---

.codecov.yml
Sources/ParseSwift/Authentication/3rd Party/ParseApple.swift
Tests/ParseSwiftTests/ParseAppleTests.swift

Parse Server expects the `identityToken` to remain in a specific format.

Fix: Apple login identityToken

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/ParseConstants.swift

This PR shows all of the files that need to be updated when preparing for a new release. The process should be as follows:

Update SDK version number

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Add modifiers to containsString, hasPrefix, hasSuffix

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Fix #86 select and exclude https://github.com/parse-community/parse-server/pull/7242

Fix query select and exclude

---

.codecov.yml
CHANGELOG.md
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/API/BatchUtils.swift
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Coding/AnyCodable.swift
Sources/ParseSwift/Coding/AnyEncodable.swift
Sources/ParseSwift/Coding/ParseCoding.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseAnonymousTests.swift
Tests/ParseSwiftTests/ParseAppleTests.swift
Tests/ParseSwiftTests/ParseAuthenticationTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseLDAPTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseOperationTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Currently, when child objects are present they are saved to the server individually which requires more network calls and overhead. This was done on purpose because child objects are discovered at the ParseEncoder level and returned as an opaque `Encodable` object. This caused issues with batch... This PR addresses the problem by making those opaque objects `AnyCodable`, allowing batch to do its thing. In addition, each batch of child objects are always sent as a transaction.
This PR is non-breaking as all of the changes are under-the-hood

Batch child objects using transactions

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/Authentication/Internal/ParseAnonymous.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Protocols/Objectable.swift
Sources/ParseSwift/Types/ParseGeoPoint.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectBatchTests.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Fix allowCustomObjectId

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook.swift
Sources/ParseSwift/Coding/ParseCoding.swift
Tests/ParseSwiftTests/ParseFacebookTests.swift

The date formatting for encoding/decoding dates was not being set properly, causing times to match on the server.
Apple recommends the following for [fixed format date representations](https://developer.apple.com/documentation/foundation/dateformatter):
```swift
let RFC3339DateFormatter = DateFormatter()
RFC3339DateFormatter.locale = Locale(identifier: "en_US_POSIX")
RFC3339DateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ" //Parse uses "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" instead
RFC3339DateFormatter.timeZone = TimeZone(secondsFromGMT: 0)
```
Fix #102

Fix date encoding/decoding

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseFacebookCombineTests.swift
Tests/ParseSwiftTests/ParseFacebookTests.swift

Let ParseFacebook accept expiresIn parameter

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseAnonymousTests.swift
Tests/ParseSwiftTests/ParseAppleTests.swift
Tests/ParseSwiftTests/ParseFacebookTests.swift
Tests/ParseSwiftTests/ParseLDAPTests.swift
Tests/ParseSwiftTests/ParseTwitterTests.swift

There was an issue when linking authTypes occurred and an error would be thrown because the `sessionToken` was missing. The fix is to account for when the server sends/doesn't send a sessionToken. Fix #108

fix throwing error when linking auth types due to missing sessionToken

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseInstallation.swift
Tests/ParseSwiftTests/ParseUserCombineTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Automatically create a new installation after it's deleted from the Keychain. A deletion typically occurs on user logout. Fix #110

Recreate new installation after deletion from keychain

---

CHANGELOG.md
ParseSwift.playground/Pages/6 - Installation.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Storage/KeychainStore.swift
Tests/ParseSwiftTests/ParseInstallationCombineTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseUserCombineTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Reasoning/discussion in #113. This is a breaking changing, but will allow for easier and more predictable use of `ParseInstallation`. If the developer wants to save the latest badge value, they should retrieve it before saving the installation.
Fix #113

ParseInstallation no longer requires dispatching to main queue

---

.codecov.yml
CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/6 - Installation.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
README.md
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Storage/KeychainStore.swift
Sources/ParseSwift/Types/ParseConfig.swift
Tests/ParseSwiftTests/MigrateOldParseInstallationTests.swift
Tests/ParseSwiftTests/ParseInstallationCombineTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

`ParseInstallation` is slightly different than other `ParseObjects` as it's created with a unique identifier (`installationId`) locally on the device and may or may not be saved depending on the app use case. This fixes a bug for when the Installation is saved to the server and the objectId of the Installation wasn't saved to the Keychain. This prevents the ability to fetch an updated Installation because fetch is based on the `objectId`. 
Fix #115 Should also fix multiple save issue mentioned in #93

Bug fix: Correctly save objectId of Installation

---

.codecov.yml
CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/LiveQuery/Messages.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Protocols/Objectable.swift
Sources/ParseSwift/Storage/ParseFileManager.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift
Tests/ParseSwiftTests/MigrateOldParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectBatchTests.swift

Can migrate the `installationId` from the iOS Objective-C SDK by initializing with  `migrateFromObjcSDK = true`.

Migrate installationId from objc SDK

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject+combine.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Adds the ability to `findAll` objects.

Add findAll query

---

CHANGELOG.md
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

A query hint can now be set using a method and its returned type is automatically inferred. In addition, a hint can now be any Encodable type instead of just a String. This is a breaking change if you were using hint.

Improve query hint

---

Sources/ParseSwift/Types/Query+combine.swift

`hint` does nothing anymore as an argument and these should have been removed in the previous PR.
No changelog needed as this is a nit.

Remove unused hint argument from publishers

---

CHANGELOG.md
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseFile+combine.swift
Sources/ParseSwift/Types/ParseFile.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseFileTests.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

The are some updates to aggregate. Aggregate technically can't be used yet in ParseSwift because it uses POST instead of

Improve aggregate by accepting any Encodable type

---

.codecov.yml
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/Types/ParseError.swift
Tests/ParseSwiftTests/APICommandTests.swift
Tests/ParseSwiftTests/ParseCloudTests.swift

Make parse error codes match latest...

Update ParseError codes

---

.github/workflows/release.yml

As noted [here](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret)...
> The token's permissions are limited to the repository that contains your workflow.
Which makes it more secure than using a personal access token which at best can be restricted to granting access to all public repos.

Use GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN

---

Sources/ParseSwift/Types/ParseError.swift

Nit in documenting `ParseError`

Fix ParseError documentation

---

.codecov.yml
CHANGELOG.md
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
README.md
Scripts/jazzy.sh
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/Coding/AnyCodable.swift
Sources/ParseSwift/Coding/AnyDecodable.swift
Sources/ParseSwift/Coding/AnyEncodable.swift
Sources/ParseSwift/Coding/ParseCoding.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift

Parse-Swift uses a custom version of the type-erased wrapper, [AnyCodable](https://github.com/Flight-School/AnyCodable). The custom version of AnyCodable isn't expected to mirror updated versions of the original AnyCodable and shouldn't be used outside of the Parse-Swift SDK. If developers want to use AnyCodable or any other type-erased wrapper within their apps/packages (SPM, cocoapods, etc.), they should create them or add AnyCodable manually.

Make type-erased wrappers internal

---

Sources/ParseSwift/Coding/Extensions.swift
Sources/ParseSwift/Coding/ParseCoding.swift
Sources/ParseSwift/Types/Query.swift

This isn't needed publicly and should be accessed through a ParseObjects: getEncoder, getJSONEncoder, and getDecoder methods.

Make ParseCoding inaccessible

---

.github/workflows/ci.yml
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (iOS).xcscheme
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (macOS).xcscheme
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (tvOS).xcscheme

Swift 5.4 was recently released. Testing compatibility of Linux build. Github Actions will automatically test the rest of the CI once it updates to Xcode 12.5.

Test against Swift 5.4

---

CHANGELOG.md
ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseCloud+combine.swift
Sources/ParseSwift/Types/ParseCloud.swift
Sources/ParseSwift/Types/ParseConfig+combine.swift
Sources/ParseSwift/Types/ParseConfig.swift
Sources/ParseSwift/Types/ParseHealth+Combine.swift
Sources/ParseSwift/Types/ParseHealth.swift
Tests/ParseSwiftTests/ParseHealthCombineTests.swift
Tests/ParseSwiftTests/ParseHealthTests.swift

Adds server health check feature by checking against the `/health` endpoint.

New Feature: Health Check

---

CHANGELOG.md
ParseSwift.playground/Pages/15 - Custom ObjectId.xcplaygroundpage/Contents.swift
ParseSwift.playground/Sources/Common.swift
ParseSwift.playground/contents.xcplayground

Some devs had [issues](https://github.com/parse-community/Parse-Swift/issues/135#issuecomment-831434691) trying to figure out how to use custom objectId so adding an example. Tested on parse-server >= 4.5.0

Add Playground example of custom objectId

---

CHANGELOG.md
ParseSwift.playground/Pages/15 - Custom ObjectId.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Protocols/Objectable.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift

Fixes issue where Swift SDK prevents fetching of Parse objects when custom objectId is enabled. This is due to checking for `createdAt` for a saved object. Close #138

Fix custom objectId fetch

---

CHANGELOG.md
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/Types/ParseFile.swift
Tests/ParseSwiftTests/ParseFileTests.swift

Should error when attempting to update a ParseFile that is already saved. It seems the parse-server doesn't support updating a ParseFile from the [server tests](https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/spec/ParseFile.spec.js) (no `PUT`) and also from what's shown in the [REST documentation](https://docs.parseplatform.org/rest/guide/#files).  Instead another file should be created and the older file should be deleted later by the developer.

Error when attempting to update ParseFile

---

Tests/ParseSwiftTests/ParseUserCombineTests.swift

Fix testcase that randomly failed due to async being incorrectly fulfilled. Reference: https://github.com/parse-community/Parse-Swift/runs/2595080285?check_suite_focus=true#step:3:1061

Fix flaky ParseUserCombine test

---

Sources/ParseSwift/Types/ParseAnalytics+combine.swift
Sources/ParseSwift/Types/ParseHealth+Combine.swift

Clean up documentation

---

ParseSwift.playground/Pages/15 - Custom ObjectId.xcplaygroundpage/Contents.swift

Changes made to playgrounds files only.

Add example of customObjectId fetching an objectId which isn't saved

---

CHANGELOG.md
Sources/ParseSwift/LiveQuery/Messages.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Allow appending of select, exclude, include, and fields

Append instead of replace when using query

---

CHANGELOG.md
ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.playground/Sources/Common.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift

Using transactions with the latest release of parse-server using mongoDB produces errors while saving. Because of this, transactions are disabled by default. If the developer wants to use transactions internally (was used for saveAll children) in the SDK, they should set `useTransactionsInternally=true` when configuring the client.
Mongo users should update to Swift SDK 1.8.1 as versions 1.2.1 - 1.8.0 use transactions by default.
Note: transactions seem to work fine with postgres.
Close #157

Don't use transactions by default for internal SDK calls

---

.github/workflows/ci.yml
README.md
Sources/ParseSwift/Parse.swift

Add description of useTransactionsInternally to docs

---

CHANGELOG.md
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/Query.swift

Improve query comparison

---

CHANGELOG.md
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/Types/ParseError.swift
Tests/ParseSwiftTests/APICommandTests.swift
Tests/ParseSwiftTests/ParseCloudTests.swift
Tests/ParseSwiftTests/ParseErrorTests.swift

Closes #164
@cbaker6 let me know your thoughts!

new: allow for custom error codes from Parse Cloud

---

CHANGELOG.md
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
README.md
Scripts/jazzy.sh
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/Types/Pointer.swift
Tests/ParseSwiftTests/ParsePointerTests.swift

Fix saving ParseObjects with Pointers as properties 

---

CHANGELOG.md
ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery+combine.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
Tests/ParseSwiftTests/ParseLiveQueryCombineTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Provides a number of essential fixes and updates to `ParseLiveQuery`:

Fix LiveQuery reconnection bug

---

.codecov.yml
Sources/ParseSwift/LiveQuery/Messages.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Make both errors look similar to the client SDK

Align ParseLiveQuery error with ParseError

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/LiveQuery/Protocols/LiveQuerySocketDelegate.swift
Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Fixes a bug in LiveQuery when a close frame is sent from the server. The the close frame was received, all running websocket tasks were closed instead of the particular task the request was intended for. 
and reason the server closed the connection

Fix ParseLiveQuery closing all connections from server request

---

ParseSwift.podtemplate
README.md

Allows cocoapods to default to Swift 5.4. Also add documentation badge.

Update podspec to Swift 5.4

---

CHANGELOG.md
ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Storage/ParseStorage.swift
Sources/ParseSwift/Types/ParseVersion.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift
Tests/ParseSwiftTests/ParseVersionTests.swift

Persist current SDK version for migrating between versions

---

Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Objects/ParseUser.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Creating a `ParseUser` instance, populating its properties, and using `.signup` resulted in the added properties for the `ParseUser` not being persisted to the Keychain on the client. All the data was saving to the server correctly.
Close #186

Fixed a bug with signing up a User instance

---

Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

When a query has a limit of zero, there's no need to send the information to the server.

Don't query server when limit is zero

---

ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Types/ParseBytes.swift
Sources/ParseSwift/Types/ParseGeoPoint.swift
Sources/ParseSwift/Types/ParsePolygon.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseBytesTests.swift
Tests/ParseSwiftTests/ParseGeoPointTests.swift
Tests/ParseSwiftTests/ParsePolygonTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Adds two missing Parse types to the Swift SDK: `ParseBytes` and `ParsePolygon`.

Add ParseBytes and ParsePolygon

---

Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/ParseConfig.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Previously, `ParseUser.current` and `ParseInstallation.current` only persisted the required Parse properties to the Keychain and didn't contain any developer added properties. This was done to keep the Keychain as small as possible, but required developers to have to fetch the `ParseUser` and `ParseInstallation` to access any added properties after app restart.
This update removes those restrictions and persists all `ParseUser` and `ParseInstallation` properties to the Keychain. A side effect of this is Keychains will now be larger than they were previously, so developers should be cautious of what types of data they store to `ParseUser` and `ParseInstallation`.

Save all fields of User and Installation to keychain

---

Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/Protocols/Objectable.swift
Sources/ParseSwift/Types/Pointer.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParsePointerTests.swift

Fixed a bug where the `ParseEncoder` incorrectly detects a circular dependency when two child objects are the same. The failing test case is below:
```swift
func testAllowFieldsWithSameObject() throws {
var score = GameScore(score: 10)
var level = Level()
level.objectId = "nice"
score.level = level
score.nextLevel = level
score.ensureDeepSave { (_, _, parseError) in
XCTAssertNil(parseError)
}
}
```

Fix circular dependency detection

---

ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/API/URLCache+extensions.swift
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/ParseAnalytics.swift
Sources/ParseSwift/Types/ParseConfig.swift
Sources/ParseSwift/Types/ParseFile.swift
Sources/ParseSwift/Types/ParseHealth.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift
Tests/ParseSwiftTests/ParseFileTests.swift

Enables caching of http requests along with adding headers. Caching and additional headers can be set when initializing the SDK. Caching can also be set per request using `API.Options`.

Add caching and additional http headers

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseUser.swift

Make sure the cache is cleared when a user logs out

Clear cache on logout

---

CHANGELOG.md
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook.swift
Sources/ParseSwift/Authentication/3rd Party/ParseTwitter.swift
Tests/ParseSwiftTests/ParseFacebookCombineTests.swift
Tests/ParseSwiftTests/ParseFacebookTests.swift
Tests/ParseSwiftTests/ParseTwitterTests.swift

Closes #201.
Sets correct payload for FB login.

fix: use correct auth keys for Facebook and Twitter login

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/LiveQuery/Protocols/LiveQuerySocketDelegate.swift
Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

If the client receives an error that it's not connect, it will attempt to reconnect if max attempts haven't been reached.

Attempt to reconnect to LiveQuery server after error

---

CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Storage/ParseFileManager.swift

Make ParseFileManager public so developers can easily find the location of ParseFiles.

Make ParseFileManager public

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Check states of WebSocket during a not connected error and proceed accordingly.

ParseLiveQuery checks all states of a websocket

---

CHANGELOG.md
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

There were times where a web socket task was resumed before the proper delegates were set.

Improve LiveQuery task creation

---

CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Fix tests that cause other tests failures:
Some tests in this particular suite will continue to fail randomly since the web socket connections are not intercepted and mocked

Fix LiveQuery flaky tests

---

.codecov.yml
CHANGELOG.md
ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
Sources/ParseSwift/ParseConstants.swift
TestHostTV/Info.plist
Tests/ParseSwiftTests/ParseLiveQueryCombineTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Ensure that LiveQuery delegate always receives connection errors. Previously, an error that occurs after a resumeTask may not be passed to the delegate.

LiveQuery: Always receive and pass connection errors

---

CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

`withinMiles` and `withinKilometers` wasn't passing `sort` to `withinRadians` preventing a developer to request unsorted data.

Query withinMiles and withinKilometers can return unsorted results

---

.codecov.yml
Sources/ParseSwift/API/Responses.swift

Adds support for batch `PATCH`. Currently not used, but will make it easier to leverage once available.

Further preparation for .PATCH

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/API/API+Commands.swift
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject+combine.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Operations/ParseOperation.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Storage/KeychainStore.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift

Properly allow a mixed custom objectId environment without compromising safety checks using `.save()`. If a developer wants to ignore the objectId checks, they need to specify `isIgnoreCustomObjectIdConfig = true` each time.
Added the following warning to the documentation:
> If you are using `ParseConfiguration.allowCustomObjectId = true` and plan to generate all of your `objectId`'s on the client-side then you should leave `isIgnoreCustomObjectIdConfig = false`. Setting `ParseConfiguration.allowCustomObjectId = true` and `isIgnoreCustomObjectIdConfig = true` means the client will generate `objectId`'s and the server will generate an `objectId` only when the client does not provide one. This can increase the probability of colliding `objectId`'s as the client and server `objectId`'s may …

Allow mixed custom objectId environment

---

CHANGELOG.md
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Storage/KeychainStore.swift
Sources/ParseSwift/Storage/SecureStorage.swift
Sources/ParseSwift/Types/ParseVersion.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift

Fixes an issue on macOS based ParseSwift apps where they end up using the same Keychain. This is fixed by using the app bundle id for the keychain of each app. The issue is explained here: https://github.com/parse-community/Parse-Swift/issues/223#issuecomment-909711808
**Warning for macOS app developers only** the user who logged in last to your app will have their Keychain upgraded to the patched version. Other users/apps will either need to login again or logout then login again

Use separate Keychain for each app

---

.github/ISSUE_TEMPLATE/---1-report-an-issue.md
.github/pull_request_template.md

In preparation to enable the Parse GitHub Assistant:
- update issue template according to standardized template the bot exptects
- add PR template

ci: update github templates

---

CHANGELOG.md
ParseSwift.playground/Pages/10 - Cloud Code.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/15 - Custom ObjectId.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/17 - SwiftUI - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
Sources/ParseSwift/API/URLSession+extensions.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseError.swift
Sources/ParseSwift/Types/ParseFile.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

Saving a `ParseObject` with a `ParseFile` halts the main queue. 
Related issue: #229 
Save `ParseObject`'s with embedded `ParseFile`s save on the background queue.

fix: Saving ParseFiles occurs on the background queue

---

.codecov.yml
CHANGELOG.md
README.md
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Internal/BaseParseInstallation.swift
Sources/ParseSwift/LiveQuery/Messages.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/ParseConfig.swift
Tests/ParseSwiftTests/APICommandTests.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Installation not saving to the Keychain correctly, preventing the use of push notifications.
Related issue: #235
Save a `BaseParseInstallation` when initializing the SDK that can later be casted to the developers `ParseInstallation`.
When upgrading from previous versions of the SDK, this patch will attempt to fetch the installation from the Parse Server if it's available or else it will create a new one. If you added custom properties to your Installation you should call `Installation.current?.fetch` during SDK initialization to get the latest from the parse-server. Developers should also use cloud code/jobs to clean up any old installations that aren't being used anymore on the server.

fix: Installation not saving to keychain correctly, returning nil instead

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/CloudViewModel.swift
Sources/ParseSwift/Types/QueryViewModel.swift
Tests/ParseSwiftTests/ParseUserTests.swift

When a current user email isn't modified, it shouldn't be sent to the server or else it will trigger verify email.
Related issue: #239 
Only encode email if it's modified.

fix: Don't encode unmodified email when updating a user

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Types/ParseError.swift
Tests/ParseSwiftTests/ParseErrorTests.swift

Related issue: #251
Add the ability to easily compare Swift Errors with ParseErrors.

feat: Added error comparing

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseObject+combine.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Operations/ParseOperation.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseConfig+combine.swift
Sources/ParseSwift/Types/ParseFile.swift
Sources/ParseSwift/Types/Pointer.swift
Tests/ParseSwiftTests/ParseOperationTests.swift
Tests/ParseSwiftTests/ParsePointerTests.swift

ParseFile should use the default cache policy set when initializing the SDK.
Remove `NSObject` comparison from `ParseOperation` set as it doesn't work well with non `NSObjects`.
Switched policy to previous default policy and cleaned up documentation.

fix: default cache policy for ParseFile uses SDK default

---

Sources/ParseSwift/API/API.swift
Sources/ParseSwift/Types/Query.swift

Some places in the docs mention Parse Server > 4.5.0 which really means 5.0.0+
Change all relevant references to 5.0.0+

docs: update parse server version reqs

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift

Make sure cache is deleted during first start of app when `deleteKeychainIfNeeded = true` 
Delete the cache on first restart when `deleteKeychainIfNeeded = true`

fix: delete all stored Parse data and cache when deleteKeychainIfNeeded is true

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/contents.xcplayground
README.md
Tests/ParseSwiftTests/ParseQueryTests.swift

Missing examples of async/await in Playgrounds.
Add a simple async/await query example to Playgrounds to show users how to take advantage.
I won't add anymore of these as they will continue to make Playgrounds look ugly until Xcode 13.2 is released. Also, async/await is straight forward and look similar to synchronous examples.

docs: add async/await playground example

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseACL.swift
Tests/ParseSwiftTests/ExtensionsTests.swift
Tests/ParseSwiftTests/ParseACLTests.swift
Tests/ParseSwiftTests/ParseAnalyticsTests.swift
Tests/ParseSwiftTests/ParseInstallationAsyncTests.swift
Tests/ParseSwiftTests/ParseInstallationCombineTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift
Tests/ParseSwiftTests/ParseSessionTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Developers currently have to add the `defaultACL` to their `ParseObject`'s. The SDK should be able to handle this.
Check if there is currently no ACL set on an object, if there's non, but there's a default ACL available, use it. This occurs before saving/creating an object to the server.

fix: use default ACL on newly created ParseObjects

---

.github/workflows/ci.yml
README.md
Tests/ParseSwiftTests/ParseOperationTests.swift

SDK is capable be being built for Windows, but a windows build currently isn't in the CI.
Add windows build to CI

ci: add Windows build

---

CHANGELOG.md
README.md
Sources/ParseSwift/API/API+NonParseBodyCommand.swift
Sources/ParseSwift/ParseConstants.swift

Changes in #291 refactoring important asynchronous callbacks. There was one missed which can cause a crash while queuing.
After querying the server, be sure to dispatch back to the proper queue

fix: query objects doesn't dispatch properly

---

.codecov.yml
ParseSwift.playground/Pages/12 - Roles and Relations.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Types/ParseOperation.swift
Sources/ParseSwift/Types/ParseRelation.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseOperationTests.swift
Tests/ParseSwiftTests/ParseRelationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift

`ParseRelation` can use some additional methods to make it easier to create and query relations.
Add the following:
- `ParseRelation`: `func add<U>(_ objects: [U]) throws -> ParseOperation<T> where U: ParseObject`
- `ParseRelation`: `func remove<U>(_ objects: [U]) throws -> ParseOperation<T> where U: ParseObject`
- `ParseRelation`: `func query<U>(_ key: String, parent: U) throws -> Query<T> where U: ParseObject`
- `ParseRelation`: `func query<U>(_ key: String, child: U) throws -> Query<U> where U: ParseObject`
- `ParseRelation` Playground save/query example
- `QueryConstraint`: `func related(key: String) -> QueryConstraint`
- `QueryConstraint`: `func related <T>(object: T) throws -> QueryConstraint where T: ParseObject`
- `QueryConstraint`: `func related <T>(object: …

feat: improve ParseRelation by adding more methods

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/release.yml

Xcode in the CI needs to be bumped to 13.2 in order to build
Bump to Xcode 13.2 in the release CI

ci: bump release to Xcode 13.2

---

Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Tests/ParseSwiftTests/ParseAnalyticsTests.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseSessionTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

The SDK currently throws an `.unknown` error specifying the objectId is missing (when it's actually missing), but it can actually throw `.missingObjectId` from within the SDK.
Throw `.missingObjectId` in the above situation.

fix: throw .missingObjectId error when fetching

---

Sources/ParseSwift/Types/ParsePolygon.swift
Sources/ParseSwift/Types/Query.swift

SDK currently duplicates code for variadic calls that have array counterparts.
Reduce call sites by having all methods with variadic arguments call their array counterparts.
This not only reduces the code footprint, but removes the chances of different implementations between methods.

refactor: make variadic call array counterparts

---

.codecov.yml
Sources/ParseSwift/Extensions/URLCache.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Tests/ParseSwiftTests/ExtensionsTests.swift
Tests/ParseSwiftTests/ParseEncoderTests/TestParseEncoder.swift
Tests/ParseSwiftTests/ParseSessionTests.swift

Additional headers should be able to take a dictionary of `[AnyHashable: Any]` as specified by https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411532-httpadditionalheaders
Let additional headers accept `[AnyHashable: Any]`.

fix: let additional headers take any type

---

.swiftlint.yml
Sources/ParseSwift/Types/QueryWhere.swift

In latest version of Xcode, the linter sometimes tries to lint dummy files added by Xcode in the `DerivedData` folder, causing errors.
Make SwiftLint ignore the `DerivedData` folder.

fix: don't lint DerivedData and remove force unwrapping

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
README.md
Sources/ParseSwift/Types/Query+async.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Sources/ParseSwift/Types/QueryConstraint.swift

Update documentation to reflect changes in support for the [relative](https://github.com/parse-community/Parse-Swift/blob/1636285beb51d9bf33230d5f80a9db5f8ec8707c/Sources/ParseSwift/Types/QueryConstraint.swift#L365-L382) `QueryConstraint` for Postgres.
- Update relevant documentation
- nit documentation, `mongoDB` -> `MongoDB`

docs: update relative QueryConstraint support for Postgres

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Authentication/3rd Party/ParseApple/ParseApple+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseApple/ParseApple.swift
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook/ParseFacebook+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook/ParseFacebook+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseFacebook/ParseFacebook.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGithub/ParseGitHub+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGithub/ParseGitHub+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGithub/ParseGitHub.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGoogle/ParseGoogle+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGoogle/ParseGoogle+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseGoogle/ParseGoogle.swift
Sources/ParseSwift/Authentication/3rd Party/ParseLinkedIn/ParseLinkedIn+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseLinkedIn/ParseLinkedIn+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseLinkedIn/ParseLinkedIn.swift
Sources/ParseSwift/Authentication/3rd Party/ParseTwitter/ParseTwitter+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseTwitter/ParseTwitter.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Types/Pointer.swift
Tests/ParseSwiftTests/ParseACLTests.swift
Tests/ParseSwiftTests/ParseGitHubCombineTests.swift
Tests/ParseSwiftTests/ParseGitHubTests.swift
Tests/ParseSwiftTests/ParseGoogleCombineTests.swift
Tests/ParseSwiftTests/ParseGoogleTests.swift
Tests/ParseSwiftTests/ParseLDAPAsyncTests.swift
Tests/ParseSwiftTests/ParseLDAPCombineTests.swift
Tests/ParseSwiftTests/ParseLinkedInCombineTests.swift
Tests/ParseSwiftTests/ParseLinkedInTests.swift

Currently, developers have to manually create an authData dictionary with the correct credentials to [login](http://parseplatform.org/Parse-Swift/api/Protocols/ParseAuthentication.html#/s:10ParseSwift0A14AuthenticationP5login8authData7options13callbackQueue10completionySDyS2SG_ShyAA3APIV6OptionOGSo17OS_dispatch_queueCys6ResultOy17AuthenticatedUserQzAA0A5ErrorVGctF) or [link](http://parseplatform.org/Parse-Swift/api/Protocols/ParseAuthentication.html#/s:10ParseSwift0A14AuthenticationP4link8authData7options13callbackQueue10completionySDyS2SG_ShyAA3APIV6OptionOGSo17OS_dispatch_queueCys6ResultOy17AuthenticatedUserQzAA0A5ErrorVGctF) user accounts. This can be more error prone and makes it harder to unlink users.
Related issue: #55 
Add auth support for the Github, Google, and Linkedin, similar …

feat: add auth support for Github, Google, Linkedin

---

Sources/ParseSwift/Authentication/3rd Party/ParseGithub/ParseGitHub.swift
Sources/ParseSwift/Authentication/3rd Party/ParseLinkedIn/ParseLinkedIn.swift
Tests/ParseSwiftTests/ParseGitHubCombineTests.swift
Tests/ParseSwiftTests/ParseGitHubTests.swift
Tests/ParseSwiftTests/ParseLinkedInCombineTests.swift
Tests/ParseSwiftTests/ParseLinkedInTests.swift

Recently added auth: `ParseGitHub` and `ParseLinkedIn` properties are cased `gitHub` and `linkedIn` respectively.
Make all casing lower case for properties named after their auth type. This makes of the `ParseAuthentication` auths look the same and makes it easier to copy/paste/modify new adapters in the future.

refactor: make properties for ParseGitHub, ParseLinkedIn lowercase

---

CHANGELOG.md
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query+async.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

The Swift SDK can't explain MongoDB queries due to a bug on the server-side response. PR https://github.com/parse-community/parse-server/issues/7440 was created on the server, but the server team has chosen not to fix the code.
Originally discussed in: https://community.parseplatform.org/t/explain-result-in-parseswift/1557
Related issue: #N/A https://github.com/parse-community/parse-server/issues/7442
Add a new internal response type that doesn't expect `results` to be an array. When the user wants to explain a mongo query, they set the flag, `isUsingMongoDB=true`. This allows the mongo explained queries to use the same methods as the ones already in the SDK.

feat: add explain MongoDB queries

---

Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/ParseError.swift

Comparing bools lead to increase build times. Reference: https://forums.swift.org/t/boolean-comparison-causes-extremely-slow-compilation/41609
Remove unnecessary comparisons knocks ~3 seconds off of build.

refactor: remove bool comparisons to decrease build times

---

CHANGELOG.md
Sources/ParseSwift/Coding/ParseCoding.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/IOS13Tests.swift
Tests/ParseSwiftTests/ParseBytesTests.swift
Tests/ParseSwiftTests/ParseCloudTests.swift
Tests/ParseSwiftTests/ParseConfigTests.swift
Tests/ParseSwiftTests/ParseEncoderTests/TestParseEncoder.swift
Tests/ParseSwiftTests/ParseFileTests.swift
Tests/ParseSwiftTests/ParseGeoPointTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift
Tests/ParseSwiftTests/ParseObjectBatchTests.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseOperationTests.swift
Tests/ParseSwiftTests/ParsePointerTests.swift
Tests/ParseSwiftTests/ParsePolygonTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseRelationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift

When using the SDK encoders, the keys are not required to be sorted. Since a JSON encoded string is sometimes used a keys or compared directly internally, it can lead to matches not found when saving `ParseObject`'s that have children `ParseObect`'s.
This is also the reason why multiple tests are disabled for Linux and Windows.
Make all SDK encoders sort keys.

fix: always sort JSON encoded keys

---

CHANGELOG.md
README.md
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/Objects/ParseInstallation+async.swift
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject+async.swift
Sources/ParseSwift/Objects/ParseObject+combine.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser+async.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/Query+async.swift
Sources/ParseSwift/Types/Query+combine.swift
Sources/ParseSwift/Types/Query.swift
Sources/ParseSwift/Types/QueryConstraint.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift
Tests/ParseSwiftTests/ParseQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Some naming in the SDK doesn't match Swift Style guide
Move to matching [Swift Style Guide](https://google.github.io/swift/#identifiers). Breaking, but the compiler should get most of these correct. Many people are probably not using most of these as they have default values...
Makes the following changes:
- `isUsingMongoDB -> usingMongoDB`
- `isIgnoreCustomObjectIdConfig -> ignoringCustomObjectIdConfig` 
- `isUsingEQ -> usingEqComparator`

refactor: user Swift convention for parameter names

---

.github/workflows/ci.yml
CHANGELOG.md
Package.swift
README.md

The Package.swift currently specifies 5.1 as the tool version, preventing the SDK and developers to take advantage of the latest features of the 5.5 toolchain such as DocC and tutorials.
Bump the SPM toolchain to 5.5. This will benefit developers using Xcode 13+ as they will be able to access the docs and tutorials when building their apps in Xcode along with those using SPM on Linux, Android, and Windows. 
**Breaking Change** for those developers who want to use ParseSwift 4.0.0+ with < Xcode 13 and depend on the SDK using SPM. These developers should either update their Xcode to 13+ or will need to use Cocoapods or Carthage to depend on the Swift SDK for now on.

feat: bump SPM toolchain to 5.5

---

Sources/ParseSwift/Documentation.docc/ParseSwift.tutorial

Wrong image filename in tutorial.
Change filename to `parse-swift.png`.
Image now shows correctly:

docs: fix image in tutorial

---

CHANGELOG.md
ParseSwift.playground/Pages/12 - Roles and Relations.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Authentication/3rd Party/ParseApple/ParseApple.swift
Sources/ParseSwift/Authentication/3rd Party/ParseLDAP/ParseLDAP.swift
Sources/ParseSwift/Authentication/3rd Party/ParseTwitter/ParseTwitter.swift
Sources/ParseSwift/Authentication/Internal/ParseAnonymous.swift
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseRole.swift
Sources/ParseSwift/Types/ParseACL.swift
Sources/ParseSwift/Types/ParseRelation.swift
Sources/ParseSwift/Types/Pointer.swift
Tests/ParseSwiftTests/ParseRelationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift

Currently a `ParseRelation` isn't `Decodable`. This is because decoding a `ParseRelation` doesn't yield a "usable" `ParseRelation` out-of-the-box. 
See discussion here: https://github.com/parse-community/Parse-Swift/pull/294#issuecomment-1009878869
Make `ParseRelation` conform to `Codable` and add methods to make decoded stored `ParseRelation`s "usable". `ParseObject`s can now contain properties of ParseRelation<Self>. In addition, `ParseRelation`s can now be made from `ParseObject` pointers. Also removed the need to specify the child object for a `ParseRelation` query as this can be type inferred by the developer.
**Breaking Changes** to both `ParseRelation` and `ParseRole`. For ParseRole, the computed properties: users and roles, are now optional. The queryRoles …

feat: improve ParseRelation and ParseRole

---

Sources/ParseSwift/Types/ParseRelation.swift

Swift 5.1 currently isn't building because it can't use keyPath's for mapping (introduced in Swift 5.2). Broken build: https://swiftpackageindex.com/builds/DA81E358-53AA-4FA4-9532-7A727053DF1C
Use old style map to build on Swift 5.1.

fix: keyPath issue breaking Swift 5.1 build

---

CHANGELOG.md
ParseSwift.playground/Pages/3 - User - Sign Up.xcplaygroundpage/Contents.swift
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/Objects/ParseUser+async.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Tests/ParseSwiftTests/ParseUserAsyncTests.swift
Tests/ParseSwiftTests/ParseUserCombineTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Also related to https://github.com/parse-community/parse-server/issues/7784

feat: add verifyPassword to ParseUser

---

.codecov.yml
CHANGELOG.md
README.md
Sources/ParseSwift/Objects/ParseInstallation+async.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject+async.swift
Sources/ParseSwift/Objects/ParseUser+async.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/ParseAnalytics+async.swift
Sources/ParseSwift/Types/ParseFile+async.swift
Tests/ParseSwiftTests/APICommandTests.swift
Tests/ParseSwiftTests/ParseAnanlyticsAsyncTests.swift
Tests/ParseSwiftTests/ParseFileAsyncTests.swift
Tests/ParseSwiftTests/ParseInstallationAsyncTests.swift
Tests/ParseSwiftTests/ParseObjectAsyncTests.swift
Tests/ParseSwiftTests/ParseUserAsyncTests.swift
Tests/ParseSwiftTests/ParseUserCombineTests.swift

Async/await methods that have void returns won't throw errors received from the server; particularly `delete()`, `logout()`, `ParseUser.verif...()`, and `ParseAnalytics` methods. They would on throw http errors.
In addition, some places in the code still force unwrap or can be done with less code.
The the returned value of async/await void methods and throw errors if needed.
Remove force unwrapping and clean up code.

fix: some async/await methods won't throw errors

---

CHANGELOG.md
ParseSwiftTestsmacOS/Info.plist
ParseSwiftTeststvOS/Info.plist
Sources/ParseSwift/Objects/ParseUser+async.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
TestHost/Info.plist
TestHostTV/Info.plist
Tests/ParseSwiftTests/ParseFileTests.swift
Tests/ParseSwiftTests/ParseLiveQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseLiveQueryCombineTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Arbitrary loads should only be enabled for localhost when testing.
Improve the way TestHost's connect to localhost during testing.

test: improve localhost connections

---

.codecov.yml
CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseOperation.swift
Tests/ParseSwiftTests/ParseRelationTests.swift
Tests/ParseSwiftTests/ParseRoleTests.swift

When the SDK is allowing custom `objectId`'s, new `users` and `roles` can't be saved to `ParseRole`'s. 
This occurs because a `ParseRelation` has a target of `Pointer<ParseObject>`. Since a Parse Pointer doesn't have `createdAt`, an error is being thrown.
Since an `ParseOperation` can occur on a `ParseObject` or a `ParseRelation`, only check if the `objectId` is present on the target.

fix: allow ParseRole to save when using custom objectId's

---

CHANGELOG.md
ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Tests/ParseSwiftTests/ParseLiveQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseLiveQueryCombineTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

`ParseLiveQuery` uses a static method, `getDefault()` to access the default client. A computed property is more swifty.
Also missing some documentation in LiveQuery.
Replace getDefault() with a the `defaultClient` static computed property. Set `getDefault()` for deprecation in ParseSwift 5.0.0.

refactor: add defaultClient to LiveQuery to replace getDefault()

---

CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParsePolygon.swift
Sources/ParseSwift/Types/QueryConstraint.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

Currently the only way to create `or`, `nor`, and `and` `Query's` is by passing in an array of queries. There's no ability to pass a variadic amount of queries.
Add variadic methods that call through to the array methods.

feat: add variadic QueryConstraint methods

---

Sources/ParseSwift/Coding/AnyDecodable.swift
Sources/ParseSwift/Coding/AnyEncodable.swift
Tests/ParseSwiftTests/AnyCodableTests/AnyCodableTests.swift
Tests/ParseSwiftTests/AnyCodableTests/AnyEncodableTests.swift

Improve the ability of the internal AnyCodable to encode Encodable.
Add more test cases.

fix: improve codable's

---

CHANGELOG.md
Scripts/generate-documentation
Sources/ParseSwift/ParseConstants.swift

docs: fix API links

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/release.yml

GitHub actions checkout is currently not running on the latest version along with Xcode
Bump major version of actions checkout and minor version of Xcode in CI

ci: bump major version of actions checkout

---

CHANGELOG.md
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Objects/ParseSession.swift
Sources/ParseSwift/Types/ParseAnalytics.swift
Tests/ParseSwiftTests/ParseAnalyticsTests.swift
Tests/ParseSwiftTests/ParseLiveQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseLiveQueryCombineTests.swift

`ParseLiveQuery` had some extra methods to set/get the `defaultClient`.
- Allow setting/getting the default LiveQuery client using only one property and deprecate others
- Show compile time warnings and suggested updates when a developer uses deprecated code

feat: allow LiveQuery client to be set using defaultClient property

---

CHANGELOG.md
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Objects/ParseInstallation+async.swift
Sources/ParseSwift/Objects/ParseInstallation+combine.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject+async.swift
Sources/ParseSwift/Objects/ParseObject+combine.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser+async.swift
Sources/ParseSwift/Objects/ParseUser+combine.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

`includeAll` should be a computed property since it doesn't take any arguments.
Add an `includeAll` computed property to `Query` and deprecate `includeAll()`. Improve documentation of `fetch(includeKeys...)` to mention use of "*" is only one level deep.

feat: add includeAll computed property to Query

---

CHANGELOG.md
Package.swift
Package@5.1.swift

`macCatalyst` isn't specified in `Package.swift`. The [Xcode 13.4 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_4-release-notes) mentions this can cause an issue:
> Swift Playgrounds app projects with package dependencies fail to build for Mac Catalyst when a package specifies .iOS(...) in its platforms array in the manifest, but doesn’t specify .macCatalyst(...)
Add `macCatalyst` to `Package.swift`.

feat: add macCatalyst to SPM

---

CHANGELOG.md
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift
Tests/ParseSwiftTests/ParseQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseQueryViewModelTests.swift

There's currently no computed property `.query` on `ParseObjects`, the only way to get this is by using `.query`.
Add `.query` computed property to `ParseObject` and add a default value to `query(_ constraints: [QueryConstraint] = [])` to ensure `.query()` still works and doesn't break the SDK.

feat: add query computed property to ParseObject

---

CHANGELOG.md
Sources/ParseSwift/Extensions/Date.swift
Sources/ParseSwift/Types/ParseGeoPoint.swift
Sources/ParseSwift/Types/Query.swift

There are no properties for converting a `ParseGeoPoint` to `CLLocation` and `CLLocationCoordinate2D`, only methods.
Created computed properties named `toCLLocation` and `toCLLocationCoordinate2D` and deprecate `toCLLocation()` and `toCLLocationCoordinate2D()`. In addition, improve the documentation for these properties.

feat: add toCLLocation and toCLLocationCoordinate2D to ParseGeoPoint

---

CHANGELOG.md
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseInstallationTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

- Since the server `includeAll` only provides one level deep, it's currently not possible in the Swift SDK to specify `includeAll` along with additional `include` keys, preventing the ability to request the server to `includeAll` one level deep and individually specify multiple level deep includes
- When fetching with `include`, it's currently possible to send duplicate keys to the server because the `include` argument is an array. Though the server has a dedupe process to handle this, the client will send extra strings when this occurs
- Revery `includeAll` property addition and method deprecation in #362 
Related issue: #359
- Allow `includeAll` key to be sent with additional `include` keys. Note that as of today, it doesn't look like the server has this feature implemented and will …

feat: allow includeAll with additional includes

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Authentication/3rd Party/ParseInstagram/ParseInstagram+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseInstagram/ParseInstagram+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseInstagram/ParseInstagram.swift
Tests/ParseSwiftTests/ParseInstagramAsyncTests.swift
Tests/ParseSwiftTests/ParseInstagramCombineTests.swift
Tests/ParseSwiftTests/ParseInstagramTests.swift

This PR is for adding Instagram to 3rd party login providers.
Related issue: #55

feat: add Instagram authentication

---

CHANGELOG.md
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
Sources/ParseSwift/LiveQuery/LiveQueryConstants.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Protocols/ParseHookRequestable.swift
Sources/ParseSwift/Protocols/ParseHookTriggerable.swift
Sources/ParseSwift/Types/ParseHookFunctionRequest.swift
Sources/ParseSwift/Types/ParseHookTriggerRequest.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseHookFunctionRequestCombineTests.swift
Tests/ParseSwiftTests/ParseHookFunctionRequestTests.swift
Tests/ParseSwiftTests/ParseHookTriggerRequestTests.swift
Tests/ParseSwiftTests/ParseHookTriggerTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

In order to create a `ParseFile` trigger, the developer has to know to pass `@File` for `className`. Similarly, the developer also needs to pass `@Connect` for `.beforeConnect`.
Fixes some issues with decoding query properties from the server.
Add another initializer that can determine what `className` to create the trigger for based on the trigger type.

feat: add support for ParseFile and beforeConnect triggers

---

CHANGELOG.md
ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
Sources/ParseSwift/LiveQuery/Messages.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

When using `ParseLiveQuery`, developers current have to call the `fields` method on query even though they may have already called `select`. This requires the developer to have to take an additional step when using Live Query.
When using the `Query` for `ParseLiveQuery`, setting `fields` will take precedence over `select`. If `fields` are not set, the `select` keys will be used.

fix: use select for ParseLiveQuery when fields are not present

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Authentication/3rd Party/ParseSpotify/ParseSpotify+async.swift
Sources/ParseSwift/Authentication/3rd Party/ParseSpotify/ParseSpotify+combine.swift
Sources/ParseSwift/Authentication/3rd Party/ParseSpotify/ParseSpotify.swift
Tests/ParseSwiftTests/ParseSpotifyAsyncTests.swift
Tests/ParseSwiftTests/ParseSpotifyCombineTests.swift
Tests/ParseSwiftTests/ParseSpotifyTests.swift

This PR is for adding Spotify to 3rd party login providers.
Related issue: #55

feat: add Spotify authentication

---

CHANGELOG.md
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParsePolygon.swift
Sources/ParseSwift/Types/QueryConstraint.swift
Tests/ParseSwiftTests/ParsePolygonTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift

The `withinPolygon` `QueryConstraint` currently does not encode `ParseGeoPoint`'s or `ParsePolygon` correctly.
Related issue: #380

fix: polygon query not encoding properly

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseInstallation+async.swift
Sources/ParseSwift/Objects/ParseObject+async.swift
Sources/ParseSwift/Objects/ParseUser+async.swift

If you want to execute save() or fetch(),... the function returns the ParseObject. If you don't need it you need to cancel it out with an underscore replacement.
Related issue: #384
`@discardableResult` adds the possibility to skip the result as developer.
It's up to the developer to decide whether they use the result or not.

feat: add discardableResult to ParseObject methods

---

.spi.yml
Sources/ParseSwift/LiveQuery/Subscription.swift
Sources/ParseSwift/LiveQuery/SubscriptionCallback.swift
Sources/ParseSwift/Objects/ParseInstallation.swift

The compiler doesn't like for Swift based `open` methods to be declared in extensions. More info [here](https://stackoverflow.com/a/55365945). When a method is `open` in Xcode 14, a warning is thrown by the compiler.
Move open methods inside their respective classes.

refactor: move open class methods from extension to class

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.spi.yml
CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/API/API+NonParseBodyCommand.swift
Sources/ParseSwift/API/API.swift
Sources/ParseSwift/Extensions/Dictionary.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseFileTests.swift
Tests/ParseSwiftTests/ParseQueryAsyncTests.swift
Tests/ParseSwiftTests/ParseQueryCacheTests.swift
Tests/ParseSwiftTests/ParseQueryCombineTests.swift
Tests/ParseSwiftTests/ParseQueryTests.swift
Tests/ParseSwiftTests/ParseQueryViewModelTests.swift

All queries currently use `POST` requests, preventing the ability to leverage the cache policies available in the SDK.
Related issue: #382 
Enable all queries to use `GET` requests by default so queries are cached. Developers can change the default request behavior for all queries by setting `usingPostForQuery = true` to not cache any of the queries. Setting `usingPostForQuery = true` can be useful when using the Swift SDK on the server-side as many developers will not want the server caching queries.

feat: enable query caching by using GET instead of POST

---

.codecov.yml
Sources/ParseSwift/Extensions/URLSession.swift

Decoding errors from "error decoding parse server response" can be quite tricky as the error log doesn't provide anything helpful.
Let's say you have a struct with the key `firstName` as Int, and Parse Server sends a `firstName` as string.
The error you will get is:
`The data couldn’t be read because it isn’t in the correct format`, which isn't very helpful.
This PR changes the error to print:
`typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "firstName", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil))`

feat: improve logging of decoding errors

---

.codecov.yml
CHANGELOG.md
ParseSwift.playground/Sources/Common.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Storage/KeychainStore.swift
Sources/ParseSwift/Types/ParseConfiguration.swift

#378 Set all queries to the macOS Keychain to `kSecUseDataProtectionKeychain == true` by default. Though this is [recommended by Apple](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain) to make the macOS and iOS Keychains behave the same way, it causes the issue of preventing saved items to the Keychain from being queried in Swift Playgrounds and other macOS environments (SPM XCTest) that do not have the ability to configure the Keychain.
For macOS, default to not setting `kSecUseDataProtectionKeychain == true` and provide the `usingDataProtectionKeychain` option when configuring the SDK. Developers can decide to set `usingDataProtectionKeychain == true` which will cause all macOS queries to use `kSecUseDataProtectionKeychain == true` …

fix: default to setting use data protection to false for macOS Keychain

---

CHANGELOG.md
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseFile.swift
Tests/ParseSwiftTests/ParseFileTests.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

Attempting to fetch or save a file locally that has a directory e.g. `test/file.svg` causes the Swift SDK to throw an error on the client because it attempts to create the directory structure in the filename instead of just taking the filename.
Note: This does not fix the issue of saving ParseFiles with directories in their names to the server as that issue appears to be server-side and not interpreting strict JSON.
Only use the file name when saving ParseFile's locally and ignore the directories as they are unnecessary.

fix: saving ParseFiles locally do not throw error

---

.codecov.yml
Sources/ParseSwift/Documentation.docc/ParseSwift.md
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/Types/ParseConfiguration.swift
Tests/ParseSwiftTests/ParseLiveQueryTests.swift

The changes in #397 removed the links to the `Topics` section in the current documentation.
Add back the links.

docs: add back SDK init links under Topics section

---

MIGRATION.md
README.md

Related issue: https://github.com/parse-community/Parse-Swift/issues/393
Adds an early version of a migration guide from the Parse ObjC SDK.
n/a

docs: add Parse ObjC SDK migration guide

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseObject.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

After a developer begins mutating/updating a `ParseObject` that already has an `objectId` via `mergeable` or some other method that allows the developer to save the `ParseObject` using the [Parse Servers quirky patch](https://github.com/parse-community/Parse-Swift/pull/315#issuecomment-1013332881). The only way to revert a specific `KeyPath` back to its original value is by setting it based on a local stored version or remembering what that value was.
Leverage the `originalData` property to allow developers to revert specific `KeyPath`'s or the whole `ParseObject`.
Example usage:
```swift
/* 
Assuming `score` is a GameScore `ParseObject` which was already saved and has the following properties:
- objectId = "yolo"
- name = "Frazier"
- points = 19
*/
// Reverting the …
```

feat: add revertKeyPath() and revertObject() methods to ParseObject

---

.codecov.yml
CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift
Sources/ParseSwift/Documentation.docc/ParseSwift.md
Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/Objects/ParseInstallation.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Objects/ParseUser.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/ParseACL.swift
Sources/ParseSwift/Types/ParseConfig.swift
Sources/ParseSwift/Types/ParseConfiguration.swift
Sources/ParseSwift/Types/ParseFile.swift
Sources/ParseSwift/Types/ParseOperation+async.swift
Sources/ParseSwift/Types/ParseOperation+keyPath.swift
Sources/ParseSwift/Types/ParseOperation.swift
Sources/ParseSwift/Types/ParseVersion.swift
Sources/ParseSwift/Types/Query.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseOperationAsyncTests.swift
Tests/ParseSwiftTests/ParseOperationTests.swift

The `set` operation currently requires using a tuple of the `key` String and `KeyPath`. This redundancy is because currently there is no way to get the string value of a `KeyPath` reliably without the developer supplying the correct `key` String. Errors can be reduced when using the `set` operation if only the `KeyPath` is used to set the value instead of the `key` String.
Safely unwrapping properties in Swift is easy, but can be cumbersome and require extra code. Since all properties of a `ParseObject` are required to be optional for encoding/decoding and `Parse Pointer` purposes developers usually have to write additional code to unwrap values. It would be nice if a helper method was provided that can do this.
Since the `ParseOperation` has the `ParseObject` as a …

feat: add set operation based on KeyPath

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/Documentation.docc/ParseSwift.md
Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/Objects/ParseObject.swift
Sources/ParseSwift/Parse.swift
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Protocols/ParseFileTransferable.swift
Sources/ParseSwift/Types/ParseCLP.swift
Sources/ParseSwift/Types/ParseConfiguration.swift
Sources/ParseSwift/Types/ParseFileDefaultTransfer.swift
Sources/ParseSwift/Types/ParseOperation.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift

All `ParseFile` uploads currently default to having to go to a Parse Server which then forwards to a 3rd party file storage if necessary. There's no way to directly upload files to file storage from the Swift SDK.
Add the `ParseFileTransferable` protocol which allows developers to conform to the protocol and designate how/where `ParseFile`'s are uploaded. Any object that conforms to `ParseFileTransferable` can be passed during initialization of the SDK to override the default behavior.

feat: add ParseFileTransferable protocol for direct file uploads

---

CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/Responses.swift
Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/Protocols/ParseFileTransferable.swift
Tests/ParseSwiftTests/ParseFileTransferableTests.swift

#410 added the `ParseFileTransferable` protocol which allows developers to upload `ParseFile`'s directly to different file storage mediums as oppose to uploading to a Parse Server. In order for developers to take advantage of the `ParseFileTransferable` protocol, they have to understand the response type a Parse Server will send and structure the response of the uploaded file accordingly.
If the Swift SDK provided a set of helper methods, it would remove the developer needing to understand server and client responses and ease the process.
Add the following helper methods: `makeSuccessfulUploadResponse()` and `makeDummyUploadTask()`
```swift
/**
Compose a valid file upload response with a name and url.
Use this method after uploading a file to any file storage to …
```

feat: add helper methods to ParseFileTransferable protocol

---

CHANGELOG.md
Sources/ParseSwift/Extensions/URLSession.swift
Sources/ParseSwift/ParseConstants.swift
Tests/ParseSwiftTests/ParseFileTests.swift

Accessing a cached file does not result in the actual file. This is due to the OS caching policy not directly having a way to cache `URLSessionDownloadTask`. In addition, caching files is most likely filling up the cache too quickly, removing queries and other data from cache earlier than expected.
Related issue: #413 
Remove file caching from the SDK. If developers want to check if a file has already been saved they can check the download directory for the file name. Below is [sample code](https://github.com/netreconlab/SnapCat/blob/901d7ffd424fe20217827acaa13f16b0af022cb0/SnapCat/Utility.swift#L16-L61) for reference:
```swift
@MainActor
static func fetchImage(_ file: ParseFile?) async -> UIImage? {
let defaultImage = UIImage(systemName: "camera")
guard let file = file,
let fileManager = …
```

fix: remove caching of files

---

MIGRATION.md

Offline storage is not supported by SDK, not documented in migration guide.
Add to migration guide.
n/a

docs: add unsupported offline objects to migration guide
