parse-community/Parse-Swift

.codecov.yml
Sources/ParseSwift/Coding/Extensions.swift
Sources/ParseSwift/Coding/ParseEncoder.swift
Tests/ParseSwiftTests/ParseObjectTests.swift

Was missing encoding children for nestedUnkeyedController

Fix bug in nestedUnkeyedController for ParseObjects

---

.spi.yml

Something changed on the spi page that made the badges not autogenerate properly. Hopefully this fixes it.

Fix SPI badges

---

.spi.yml

The iOS and watchOS badge returned. Seeing if tv works now.

Gaining tvOS badge

---

.github/workflows/release.yml

Release had an old dependency from when it was apart of ci.yml

Remove old dependency in workflow

---

CHANGELOG.md
ParseSwift.playground/contents.xcplayground
ParseSwift.xcodeproj/project.pbxproj
README.md
Scripts/jazzy.sh

- Remove playground duplicate line: `<page name='10 - Cloud Code'/>`
Fix #68

Fix SPM Issue: Remove duplicate playground page

---

CHANGELOG.md
ParseSwift.podspec
ParseSwift.xcodeproj/project.pbxproj
Scripts/jazzy.sh

⚡ Release 1.1.5

---

.codecov.yml
Sources/ParseSwift/Coding/AnyDecodable.swift
Sources/ParseSwift/Coding/AnyEncodable.swift

Improve type erasure

---

ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift

Show example of signing up user with additional properties. Close #149

Add example of user signup with more properties

---

Sources/ParseSwift/LiveQuery/ParseLiveQuery+combine.swift
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift

Minor updates

---

.codecov.yml
CHANGELOG.md
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/ParseConstants.swift

Prepare for 1.8.5 release

---

.codecov.yml
Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift

Make sure all data is received on the correct sync queue

LiveQuery socket changes received on queue

---

CHANGELOG.md
Sources/ParseSwift/Objects/ParseUser.swift

Make sure all connections are closed

Close all LiveQuery connections when logging out

---

.github/ISSUE_TEMPLATE/---1-report-an-issue.md

Adding Xcode to template as it can give insight to what's going on

Add Xcode version to issue template

---

CHANGELOG.md

Update version in changelog.
Related issue: #229

docs: Fix version in change log

---

.codecov.yml
ParseSwift.xcodeproj/project.pbxproj
Sources/ParseSwift/API/API+BatchCommand.swift
Sources/ParseSwift/API/API+Command.swift
Sources/ParseSwift/API/API+NonParseBodyCommand.swift
Tests/ParseSwiftTests/IOS13Tests.swift
Tests/ParseSwiftTests/ParseObjectCustomObjectIdTests.swift
Tests/ParseSwiftTests/ParseObjectTests.swift
Tests/ParseSwiftTests/ParseSessionTests.swift
Tests/ParseSwiftTests/ParseUserTests.swift

Improve readability of API.
Related issue: #233 
Separate into more files. Remove unnecessary code.

style: API Command

---

.github/workflows/ci.yml
CHANGELOG.md
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (macOS).xcscheme
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (tvOS).xcscheme
ParseSwift.xcodeproj/xcshareddata/xcschemes/ParseSwift (watchOS).xcscheme
Tests/ParseSwiftTests/ParseUserTests.swift

Codecov for some of the OS's previously wasn't uploaded to Codecov.
Add all codecov.

ci: Add codecov for all OS's

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift

Bump the CI and change log entries.

ci: bump to Xcode 13.2.1

---

Sources/ParseSwift/Objects/ParseRole.swift

Error message references wrong property.
Reference correct property.

fix: error message in queryRoles()

---

Package@5.1.swift

Add SPM 5.1 file for older systems.
Same Package file with older tools before bumping to Swift 5.5

fix: add 5.1 SPM file

---

README.md

The Snyk badge isn't applicable anymore as the Gemfile's were only used for Jazzy.
Remove Snyk badge.

docs: remove unnecessary badges

---

Scripts/generate-documentation
Sources/ParseSwift/Objects/ParseObject.swift

The bundle identifier in the DocC generation script is incorrect.
Switch to the default bundle identifier of the workspace.

docs: update docs bundle identifier

---

CHANGELOG.md
Sources/ParseSwift/Types/Query.swift

Documentation for order() of `Query` isn't accurate.
Improve descriptions.

docs: improve descriptions of order() methods

---

CHANGELOG.md
Sources/ParseSwift/ParseConstants.swift
Sources/ParseSwift/Types/QueryConstraint.swift

Nit in example in docs.
Fix documentation.

docs: improve query documentation

---

CHANGELOG.md
Sources/ParseSwift/Types/ParseFile.swift

Minor issues in spacing and grammar
Correct spaces and grammar.

docs: improve ParseFile information

---

ParseSwift.playground/Pages/1 - Your first Object.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/10 - Cloud Code.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/11 - LiveQuery.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/12 - Roles and Relations.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/13 - Operations.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/15 - Custom ObjectId.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/17 - SwiftUI - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/18 - SwiftUI - Finding Objects With Custom ViewModel.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/19 - SwiftUI - LiveQuery.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/2 - Finding Objects.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/20 - Cloud Schemas.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/21 - Cloud Push Notifications.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/23 - Cloud Hook Triggers.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/3 - User - Sign Up.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/4 - User - Continued.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/5 - ACL.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/6 - Installation.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/7 - GeoPoint.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/8 - Pointers.xcplaygroundpage/Contents.swift
ParseSwift.playground/Pages/9 - Files.xcplaygroundpage/Contents.swift
Sources/ParseSwift/Documentation.docc/ParseSwift.md
Sources/ParseSwift/Types/ParseOperation.swift
Sources/ParseSwift/Types/QueryConstraint.swift

Methods and properties to configure the SDK are scattered throughout the docs.
Place all of the methods and properties related to SDK configuration in one section.

docs: improve organization of SDK config

---

.github/workflows/ci.yml
.github/workflows/release.yml

Xcode 14 has been released.
Update CI to Xcode 14.

ci: update to Xcode 14

---

CHANGELOG.md

Documentation is saved for each version, but not easy to find in the changelog.
Add documentation for each version in the changelog.

docs: add documentation links to changelog

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Sources/ParseSwift/Types/ParseConfiguration.swift
Tests/ParseSwiftTests/InitializeSDKTests.swift

Some versions of the CI dependencies are not the same. In addition, some configuration methods are not covered in tests.
Make all CI versions the same and improve overall code coverage.

ci: improve codecov of SDK configuration
